databaseChangeLog:
  - changeSet:
      id: 0002
      author: dorian-frances
      changes:
        - renameTable:
            oldTableName: user
            newTableName: gebio_user
        - dropColumn:
            tableName: gebio_user
            columnName: username
        - addColumn:
            tableName: gebio_user
            columns:
              - column:
                  name: email
                  type: varchar(256)
                  constraints:
                    nullable: false