databaseChangeLog:
  - changeSet:
      id: 0003
      author: dorian-frances
      changes:
        - createTable:
            tableName: board
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: owner_id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: varchar(128)
                  constraints:
                    nullable: false
              - column:
                  name: template_id
                  type: uuid
                  constraints:
                    nullable: false

        - addPrimaryKey:
            tableName: gebio_user
            columnNames: id

        - addForeignKeyConstraint:
            baseTableName: board
            baseColumnNames: owner_id
            referencedTableName: gebio_user
            referencedColumnNames: id
            constraintName: fk_board_user