openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://staging-api.gebio.app
    description: Staging server

paths:
  /health/check:
    get:
      summary: Check health of the API
      operationId: check
      tags:
        - Health
      responses:
        "200":
          description: Application is running
          content:
            application/json:
              schema:
                type: string
                example: "OK, API is running"
  /api/v1/me:
    get:
      security:
        - bearerAuth: [ ]
      summary: Get current logged in user
      description: Get current logged in user
      operationId: getCurrentUser
      tags:
        - User
      responses:
        "200":
          description: Successfully retrieved current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponseContract'
              example:
                user:
                  id: 77dbf8f5-8490-4986-9863-969bf7dc6c23
                  email: john.doe@gmail.com
        "401":
          $ref: '#/components/responses/UnauthorizedError'
  /api/v1/board/{board_id}:
    get:
      security:
        - bearerAuth: [ ]
      summary: Find retrospective board by its id
      description: Find retrospective board by its id
      operationId: findById
      tags:
        - Board
      parameters:
        - name: board_id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successfully retrieved retrospective board
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindBoardResponseContract'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Board was not found
  /api/v1/board:
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a retrospective board
      description: Create a retrospective board
      operationId: createBoard
      tags:
        - Board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBoardRequestContract'
      responses:
        "201":
          description: Successfully created retrospective board
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBoardResponseContract'
        "401":
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    FindBoardResponseContract:
      description: Find retrospective board response contract
      type: object
      properties:
        board:
          $ref: '#/components/schemas/BoardContract'
    CreateBoardResponseContract:
      description: Retrospective board creation response contract
      type: object
      properties:
        board:
          $ref: '#/components/schemas/BoardContract'
    CreateBoardRequestContract:
      description: Retrospective board creation request contract
      type: object
      required:
        - title
        - templateId
      properties:
        title:
          type: string
        templateId:
          type: string
          format: uuid
    CurrentUserResponseContract:
      type: object
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/UserContract'
    BoardContract:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        templateId:
          type: string
          format: uuid
        ownerId:
          type: string
          format: uuid
        cards:
          type: array
          items:
            $ref: '#/components/schemas/CardContract'
    CardContract:
      type: object
      required:
        - id
        - content
        - color
        - position
        - ownerInfo
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        color:
          type: string
        position:
          $ref: '#/components/schemas/CardPositionContract'
        ownerInfo:
          $ref: '#/components/schemas/CardOwnerInfoContract'
        boardId:
          type: string
          format: uuid
    CardPositionContract:
      type: object
      required:
        - posX
        - posY
      properties:
        posX:
          type: integer
        posY:
          type: integer
    CardOwnerInfoContract:
      type: object
      required:
        - id
        - email
        - logo
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        logo:
          type: string
    UserContract:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
    AddCardRequestContract:
      type: object
      properties:
        boardId:
          type: string
          format: uuid
        card:
          $ref: '#/components/schemas/CardContract'
    AddCardResponseContract:
      type: object
      properties:
        card:
          $ref: '#/components/schemas/CardContract'
    UpdateCardRequestContract:
      type: object
      properties:
        boardId:
          type: string
          format: uuid
        card:
          $ref: '#/components/schemas/CardContract'
    DeleteCardRequestContract:
      type: object
      properties:
        boardId:
          type: string
          format: uuid
        cardId:
          type: string
          format: uuid
  responses:
    UnauthorizedError:
      description: Authentication is missing or invalid


