openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server
  - url: http://35.180.152.129:8080/
    description: Staging server

paths:
  /health/check:
    get:
      summary: Check health of the API
      operationId: check
      tags:
        - Health
      responses:
        "200":
          description: Application is running
          content:
            application/json:
              schema:
                type: string
                example: "OK, API is running"
  /api/v1/me:
    get:
      security:
        - bearerAuth: [ ]
      summary: Get current logged in user
      description: Get current logged in user
      operationId: getCurrentUser
      tags:
        - User
      responses:
        "200":
          description: Successfully retrieved current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponseContract'
              example:
                user:
                  id: 77dbf8f5-8490-4986-9863-969bf7dc6c23
                  email: john.doe@gmail.com
        "401":
          $ref: '#/components/responses/UnauthorizedError'

components:
  schemas:
    CurrentUserResponseContract:
      type: object
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/UserContract'
    UserContract:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
    UnauthorizedResponseContract:
      type: object
      required:
        - description
      properties:
        description:
          type: string
  responses:
    UnauthorizedError:
      description: Authentication is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedResponseContract'
          example:
            description: "Authentication is missing or invalid"



